name: Generate Snake

on:
  schedule: # Run at 12:00 AM UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/github-contribution-grid-snake.svg

      - name: Upload Snake
        uses: actions/upload-artifact@v2
        with:
          name: github-contribution-grid-snake
          path: dist/github-contribution-grid-snake.svg
